name: customized_poll_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1
publish_to: none
# Add regular dependencies here.
dependencies:
  get:
    git: https://github.com/jonataslaw/getx.git
  mgr_settings_gui:
    git: https://github.com/daslaller/mgr_settings_gui.git
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
